---
- include_role:
    name: "corpusops.roles/vars"
  tags: [elasticsearch, vars, elasticsearch_vars]
# set the cops_elasticsearch_var variable from defaults/main.yml
- include_jinja_vars:
    name: __GLOBAL__
    content: |
      ---
      {% set p = 'cops_elasticsearch_vars' %}
      {% set _vars = {p: {}} %}
      {% for i, val in vars.items() %}
      {% if i.startswith(p[:-4]) %}
      {% set _ = _vars[p].update({i.split(p[:-4], 1)[1]: val}) %}
      {% endif %}
      {% endfor %}
      #
      {% set env = _vars[p].env %}
      #
      {% set _ = env.update(_vars[p].env_overrides) %}
      #
      {% for i, val in vars.get('ansible_env', {}).items() %}
      {%  if not i.startswith(('OLDPWD', 'CWD', 'PWD',
                       'TERM', 'USER', 'HOME', 'PS1',
                       'PATH', 'ANSIBLE', 'SSH', 'LS')) %}
      {%    set _ = env.update({i: val})%}
      {%  endif %}
      {% endfor %}
      #
      {% for n in ['nginx'] %}
      {%  set _n = _vars[p].setdefault(n, {}) %}
      {%  for i, val in _vars[p].items() %}
      {%    set pref = n+'_' %}
      {%    if i.startswith(pref) %}
      {%      set _ = _n.update({
                pref.join(i.split(pref)[1:]): val}) %}
      {%    endif %}
      {%  endfor %}
      {% endfor %}
      #
      {{ _vars | to_json }}
  tags: [elasticsearch, vars, elasticsearch_vars]

