---
- name: install plugins
  shell: |
      set -e
      cd {{cops_elasticsearch_vars.root}}
      . bin/es.env
      {% for i, d  in item.items() %}
      if test ! -e "plugins/{{d}}";then
        {% set sw='--batch'%}
        {% if cops_elasticsearch_vars.version[0] > '1' %}{% set sw='--batch'%}{%endif%}
        bin/plugin install {{sw}} "{{i}}" && \
          echo "cops: Installed plugin {{i}}" >&2
      else
        echo "cops: Already installed plugin {{i}}" >&2
      fi
      {% endfor %}
  with_items: "{{cops_elasticsearch_vars.plugins.get(
      cops_elasticsearch_vars.version,
        cops_elasticsearch_vars.plugins.get(
          cops_elasticsearch_vars.version[0],
          cops_elasticsearch_vars.plugins.get('default')))}}"
  register: cops_elasticsearch_plugins_install
  notify: "{{cops_elasticsearch_vars.rhandlers}}"
  become: yes
  become_user: "{{cops_elasticsearch_vars.user}}"
  changed_when: "{{'Installed plugin' in cops_elasticsearch_plugins_install.stderr}}"
  tags: [elasticsearch, plugins, elasticsearch_plugins]

