---
- include_role:
    name: "corpusops.roles/services_http_nginx"
  vars:
    corpusops_services_http_nginx_default_vhost_is_default_server: "{{cops_elasticsearch_vars.default_vhost_is_default_server}}"
  tags: [elasticsearch,
         reverseproxy, reverseproxy_install,
         elasticsearch_reverseproxy, elasticsearch_reverseproxy_install]
- htpasswd:
    path: "{{cops_elasticsearch_vars.htpasswd}}"
    name: "{{item.key}}"
    password: "{{item.value.password}}"
    state: present
  with_dict: "{{cops_elasticsearch_vars.users}}"
  when: "(cops_elasticsearch_vars.users is not none and
          cops_elasticsearch_vars.users.keys()|length > 0)"
  tags: [elasticsearch,
         reverseproxy, reverseproxy_users,
         elasticsearch_reverseproxy, elasticsearch_reverseproxy_users]
- include_jinja_vars:
    name: __GLOBAL__
    content: {_corpusops_nginx_vhost: "{{cops_elasticsearch_vars.nginx}}"}
- include_role:
    name: "corpusops.roles/nginx_vhost"
  tags: [elasticsearch,
         reverseproxy, reverseproxy_config,
         elasticsearch_reverseproxy, elasticsearch_reverseproxy_config]
- include_jinja_vars:
    name: __GLOBAL__
    content: {_corpusops_nginx_vhost: {}}
