---
- listen: restart_cops_elasticsearch
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{item}}"
  with_items: "{{cops_elasticsearch_vars.services}}"
  when: "{{cops_elasticsearch_vars.activated and
           corpusops_vars.has_services_manager and
           (ansible_service_mgr == 'systemd')}}"
- listen: restart_cops_elasticsearch
  service:
    state: restarted
    name: "{{item}}"
  with_items: "{{cops_elasticsearch_vars.services}}"
  when: "{{cops_elasticsearch_vars.activated and
           corpusops_vars.has_services_manager and
           (ansible_service_mgr != 'systemd')}}"
- listen: reload_cops_elasticsearch
  systemd:
    daemon_reload: yes
    state: reloaded
    name: "{{item}}"
  with_items: "{{cops_elasticsearch_vars.services}}"
  when: "{{cops_elasticsearch_vars.activated and
           corpusops_vars.has_services_manager and
           (ansible_service_mgr == 'systemd')}}"
- listen: reload_cops_elasticsearch
  service:
    state: reloaded
    name: "{{item}}"
  with_items: "{{cops_elasticsearch_vars.services}}"
  when: "{{cops_elasticsearch_vars.activated and
           corpusops_vars.has_services_manager and
           (ansible_service_mgr != 'systemd')}}"
