---
- include_tasks: A0000_vars.yml
  tags: [elasticsearch, vars, elasticsearch_vars]
- include_tasks: P1000_users.yml
  tags: [elasticsearch, users, elasticsearch_users]
- include_tasks: P2000_layout.yml
  tags: [elasticsearch, layout, elasticsearch_layout]
- include_tasks: G9000_fixperms.yml
  tags: [elasticsearch, first_fixperms, elasticsearch_first_fixperms]
- include_tasks: P4000_prerequisites.yml
  tags: [elasticsearch, prerequisites, elasticsearch_prerequisites]
- include_tasks: P5000_workers.yml
  tags: [elasticsearch, workers, elasticsearch_workers]
- include_tasks: P6000_plugins.yml
  tags: [elasticsearch, plugins, elasticsearch_plugins]
- include_tasks: P7000_reverse_proxy.yml
  tags: [elasticsearch, reverse_proxy, elasticsearch_reverse_proxy]
- include_tasks: P8000_entry_point.yml
  tags: [elasticsearch, entry_point, elasticsearch_entry_point]
- include_tasks: G9000_fixperms.yml
  tags: [elasticsearch, end_fixperms, elasticsearch_end_fixperms]
