---
- block:
  - set_fact:
      cacheable: false
      only_steps: "{{only_steps|default(False)}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_s_setup_configs:            "{{cops_elasticsearch_s_setup_configs            |default(cops_elasticsearch_s_setup        |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_setup_files:              "{{cops_elasticsearch_s_setup_files              |default(cops_elasticsearch_s_setup        |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_plugins_install:          "{{cops_elasticsearch_s_plugins_install          |default(cops_elasticsearch_s_plugins      |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_prerequisites_es:         "{{cops_elasticsearch_s_prerequisites_es         |default(cops_elasticsearch_s_prerequisites|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_prerequisites_jdk:        "{{cops_elasticsearch_s_prerequisites_jdk        |default(cops_elasticsearch_s_prerequisites|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_prerequisites_pkgs:       "{{cops_elasticsearch_s_prerequisites_pkgs       |default(cops_elasticsearch_s_prerequisites|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_prerequisites_archive_es: "{{cops_elasticsearch_s_prerequisites_archive_es |default(cops_elasticsearch_s_prerequisites|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_reverse_proxy_install:    "{{cops_elasticsearch_s_reverse_proxy_install    |default(cops_elasticsearch_s_reverse_proxy|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_reverse_proxy_users:      "{{cops_elasticsearch_s_reverse_proxy_users      |default(cops_elasticsearch_s_reverse_proxy|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
      cops_elasticsearch_s_reverse_proxy_vhost:      "{{cops_elasticsearch_s_reverse_proxy_vhost      |default(cops_elasticsearch_s_reverse_proxy|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps)))}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_s_users:          "{{cops_elasticsearch_s_users         |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps))}}"
      cops_elasticsearch_s_layout:         "{{cops_elasticsearch_s_layout        |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps))}}"
      cops_elasticsearch_s_first_fixperms: "{{cops_elasticsearch_s_first_fixperms|default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps))}}"
      cops_elasticsearch_s_prerequisites:  "{{(
        cops_elasticsearch_s_prerequisites_es or
        cops_elasticsearch_s_prerequisites_jdk or
        cops_elasticsearch_s_prerequisites_pkgs or
        cops_elasticsearch_s_prerequisites_archive_es )}}"
      cops_elasticsearch_s_workers:        "{{cops_elasticsearch_s_workers       |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps))}}"
      cops_elasticsearch_s_entry_point:    "{{cops_elasticsearch_s_entry_point   |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps))}}"
      cops_elasticsearch_s_end_fixperms:   "{{cops_elasticsearch_s_end_fixperms  |default(cops_elasticsearch_lifecycle_app_setup|default(not only_steps))}}"
      cops_elasticsearch_s_setup: "{{(
          cops_elasticsearch_s_setup_configs or
          cops_elasticsearch_s_setup_files)}}"
      cops_elasticsearch_s_plugins: "{{(
          cops_elasticsearch_s_plugins_install)}}"
      cops_elasticsearch_s_reverse_proxy:  "{{(
        cops_elasticsearch_s_reverse_proxy_install or
        cops_elasticsearch_s_reverse_proxy_users or
        cops_elasticsearch_s_reverse_proxy_vhost )}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_lifecycle_app_level_1_steps: "{{(
          cops_elasticsearch_s_users or
          cops_elasticsearch_s_layout or
          cops_elasticsearch_s_first_fixperms or
          cops_elasticsearch_s_prerequisites or
          cops_elasticsearch_s_setup or
          cops_elasticsearch_s_workers or
          cops_elasticsearch_s_plugins or
          cops_elasticsearch_s_reverse_proxy or
          cops_elasticsearch_s_entry_point or
          cops_elasticsearch_s_end_fixperms)}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_lifecycle_app_push_code: "{{cops_elasticsearch_lifecycle_app|default(cops_elasticsearch_lifecycle_app_push_code|default(not only_steps))}}"
      cops_elasticsearch_lifecycle_app_setup: "{{(cops_elasticsearch_lifecycle_app_setup|default(
                                                (cops_elasticsearch_lifecycle_app|default(False)) or (
                                                  cops_elasticsearch_lifecycle_app_level_1_steps)))}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_lifecycle_app: "{{(
        cops_elasticsearch_lifecycle_app_push_code or
        cops_elasticsearch_lifecycle_app_setup)}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_lifecycle_app_lc_1_steps: "{{(
          cops_elasticsearch_lifecycle_app)}}"
  - set_fact:
      cacheable: false
      cops_elasticsearch_s_vars: "{{cops_elasticsearch_s_vars|default(cops_elasticsearch_lifecycle_app_lc_1_steps)}}"
