---
- include_tasks: lc_push_code.yml
  when: cops_elasticsearch_lifecycle_app_push_code|cops_elasticsearch_lifecycle_app
  tags: [cops_elasticsearch_lifecycle_app_push_code]
- include_tasks: lc_app.yml
  when: cops_elasticsearch_lifecycle_app_setup|cops_elasticsearch_lifecycle_app
  tags: [cops_elasticsearch_lifecycle_app]
