---
# generate password on remote box if not found
- name: "elasticsearch secret generation: {{elasticsearchsecret}}"
  include_role:
    name: corpusops.roles/get_secret_variable
  vars:
    _cops_get_secret_variable:
      name: "cops_elasticsearch_{{elasticsearchsecret}}"
      path: "/etc/elasticsearch-{{cops_elasticsearch_vars.name}}-secrets"
  when: not vars.get('cops_elasticsearch_{0}'.format(elasticsearchsecret), None)
  no_log: "{{not (cops_secret_vars_debug|default(false))}}"
- debug:
    var: "{{'cops_elasticsearch_{0}'.format(elasticsearchsecret)}}"
  register: cops_secret_value
  no_log: "{{not (cops_secret_vars_debug|default(false))}}"
- name: "Update registry with {{elasticsearchsecret}}"
  include_jinja_vars:
    content: |
      ---
      {% set d = elasticsearchsecret %}
      {% set p = 'cops_elasticsearch_' %}
      {% set v = p+d %}
      {% set n = p+'vars' %}
      {% set _vars = {} %}
      {% set _ = _vars.update(cops_secret_value) %}
      {{(_vars | copsf_registry(p, namespaced=vars[n]))[0]| to_json }}
  no_log: "{{not (cops_vars_debug|default(false))}}"
