---
- include_tasks: P1000_users.yml
  tags: [elasticsearch, users, elasticsearch_users,                   cops_elasticsearch_s_users]
  when: "cops_elasticsearch_s_users"
- include_tasks: P2000_layout.yml
  tags: [elasticsearch, layout, elasticsearch_layout,                 cops_elasticsearch_s_layout]
  when: "cops_elasticsearch_s_layout"
- include_tasks: G9000_fixperms.yml
  tags: [elasticsearch, first_fixperms, elasticsearch_first_fixperms, cops_elasticsearch_s_first_fixperms]
  when: "cops_elasticsearch_s_first_fixperms"
- include_tasks: P4000_prerequisites.yml
  tags: [elasticsearch, prerequisites, elasticsearch_prerequisites,   cops_elasticsearch_s_prerequisites]
  when: "cops_elasticsearch_s_prerequisites"
- include_tasks: P4500_setup.yml
  tags: [elasticsearch, setup, elasticsearch_setup,                   cops_elasticsearch_s_setup]
  when: "cops_elasticsearch_s_setup"
- include_tasks: P8000_entry_point.yml
  tags: [elasticsearch, entry_point, elasticsearch_entry_point,       cops_elasticsearch_s_entry_point]
  when: "cops_elasticsearch_s_entry_point"
- include_tasks: P5000_workers.yml
  tags: [elasticsearch, workers, elasticsearch_workers,               cops_elasticsearch_s_workers]
  when: "cops_elasticsearch_s_workers"
- include_tasks: P6000_plugins.yml
  tags: [elasticsearch, plugins, elasticsearch_plugins,               cops_elasticsearch_s_plugins]
  when: "cops_elasticsearch_s_plugins"
- include_tasks: P7000_reverse_proxy.yml
  tags: [elasticsearch, reverse_proxy, elasticsearch_reverse_proxy,   cops_elasticsearch_s_reverse_proxy]
  when: "cops_elasticsearch_s_reverse_proxy"
- include_tasks: G9000_fixperms.yml
  tags: [elasticsearch, end_fixperms, elasticsearch_end_fixperms,     cops_elasticsearch_s_end_fixperms]
  when: "cops_elasticsearch_s_end_fixperms"
