---
# install custom config files
- include_role: {name: corpusops.roles/configs, private: true}
  vars:
    cops_configs_templates: "{{cops_elasticsearch_vars.configs}}"
  tags: [cops_elasticsearch_s_setup_configs]
  when: [cops_elasticsearch_s_setup_configs]

- tags: [cops_elasticsearch_s_setup_files]
  when: [cops_elasticsearch_s_setup_files]
  block:
  - name: files
    file:
      path: "{{item}}"
      state: "absent"
    loop:
      - "{{cops_elasticsearch_cfg}}/logging.yml"
    changed_when: False
    tags: [cops_elasticsearch_s_setup_files]
    when: "((cops_elasticsearch_version[0]|copsf_looseversion) >=
            ('5'|copsf_looseversion))"
- tags: [cops_elasticsearch_s_setup_reverse_proxy]
  when: [cops_elasticsearch_s_setup_reverse_proxy]
  include_tasks: _setup_reverse_proxy.yml

